apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: deploy-odf-pg
policyDefaults:
  namespace: rhacm-policies
  placement:
    placementRuleName: lso-odf-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
policies:
  - name: install-odf-operator
    manifests:
      - path: subscriptions
      - path: manifests
        patches:
          - apiVersion: operator.openshift.io/v1
            kind: Console
            metadata:
              name: cluster
            spec:
              plugins:
                - odf-console
          - apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: odf-operator
              namespace: openshift-storage
            spec:
              channel: stable-4.12
              config:
                nodeSelector:
                  node-role.kubernetes.io/infra: ""
                tolerations:
                - effect: NoSchedule
                  key: node.ocs.openshift.io/storage
                  operator: Equal
                  value: 'true'
                - effect: NoSchedule
                  key: node-role.kubernetes.io/infra
                  operator: Equal
                  value: "reserved"
                - effect: NoExecute
                  key: node-role.kubernetes.io/infra
                  operator: Equal
                  value: "reserved"
